### ISSUE TITLE
mlflow: endpoint main: FileNotFoundError: ... '...Wilson_Warbler_0007_175618.txt'

### ISSUE THREAD

**Issue by mlaradji** [mlaradji/AttnGAN#5]
## Resolution
This is currently being worked on.

## Issue
Executing `mlflow run .` results in `FileNotFoundError: [Errno 2] No such file or directory: 'data/birds/text/180.Wilson_Warbler/Wilson_Warbler_0007_175618.txt'`.

## Full Trace
```
2019/07/22 05:06:51 INFO mlflow.projects: === Created directory /tmp/tmpf68x3gq6 for downloading remote URIs passed to arguments of type 'path' ===
2019/07/22 05:06:51 INFO mlflow.projects: === Running command 'source /root/miniconda3/bin/activate mlflow-27cdc5cb4fc5102311c02a771638ea390626c7b3 && python src/main.py --cfg cfg/birds/eval_bird.yml --gpu 0' in run with ID '24673d68d29441e7961122f76d802a72' === 
/content/AttnGAN/AttnGAN/src/miscc/config.py:106: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Using config:
{'B_VALIDATION': False,
 'CONFIG_NAME': 'attn2',
 'CUDA': True,
 'DATASET_NAME': 'birds',
 'DATA_DIR': 'data/birds',
 'GAN': {'B_ATTENTION': True,
         'B_DCGAN': False,
         'CONDITION_DIM': 100,
         'DF_DIM': 64,
         'GF_DIM': 32,
         'R_NUM': 2,
         'Z_DIM': 100},
 'GPU_ID': 0,
 'RNN_TYPE': 'LSTM',
 'TEXT': {'CAPTIONS_PER_IMAGE': 10, 'EMBEDDING_DIM': 256, 'WORDS_NUM': 25},
 'TRAIN': {'BATCH_SIZE': 100,
           'B_NET_D': False,
           'DISCRIMINATOR_LR': 0.0002,
           'ENCODER_LR': 0.0002,
           'FLAG': False,
           'GENERATOR_LR': 0.0002,
           'MAX_EPOCH': 600,
           'NET_E': 'DAMSMencoders/bird/text_encoder200.pth',
           'NET_G': 'models/bird_AttnGAN2.pth',
           'RNN_GRAD_CLIP': 0.25,
           'SMOOTH': {'GAMMA1': 5.0,
                      'GAMMA2': 5.0,
                      'GAMMA3': 10.0,
                      'LAMBDA': 1.0},
           'SNAPSHOT_INTERVAL': 2000},
 'TREE': {'BASE_SIZE': 64, 'BRANCH_NUM': 3},
 'WORKERS': 1}
Total filenames:  11788 001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg
Load filenames from: data/birds/train/filenames.pickle (8855)
Load filenames from: data/birds/test/filenames.pickle (2933)
Load from:  data/birds/captions.pickle
Load from: example_captions
Traceback (most recent call last):
  File "src/main.py", line 158, in <module>
    dataset.wordtoix, algo
  File "src/main.py", line 52, in gen_example
    with open(filepath, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/birds/text/180.Wilson_Warbler/Wilson_Warbler_0007_175618.txt'
2019/07/22 05:06:57 ERROR mlflow.cli: === Run (ID '24673d68d29441e7961122f76d802a72') failed ===
```

**Comment by alexitric** [comment]
I'm experiencing the same issue, it'd be interesting to know if anyone has been able to resolve
